### PR TITLE
Updating librato hubot to use the new chart API

### PR DESCRIPTION
**Pull request by bfosberry**

### CODE REVIEW

**Comment by bfosberry** [comment]
This does not use the latest snapshot on the chart api, but once that comes out we could switch

**Comment by ekosz** [comment]
:+1:

**Comment by bfosberry** [comment]
I'll leave this over the weekend and see if I can muster up some internal coffeescript review

**Comment by bfosberry** [comment]
@ekosz would you be able to bump a release, or let me know how to bump it?

**Comment by ekosz** [comment]
@bfosberry Hey sorry for the late reply. I can't seem to find your username on npmjs.com. 

Just send that over to me and I'll add you as a collaborator.

**Comment by bfosberry** [comment]
bfosberry, just created :P

thanks!

**Comment by ekosz** [comment]
@bfosberry Added! You should be able to bump the version number and run `npm publish .` now.

**Pull request merged**
